### ISSUE TITLE
Make more detailled maps available

### ISSUE THREAD

**Issue by woodwind-enr** [Akaflieg-Freiburg/enroute#105]
The OSM base map is sometimes pretty poorly detailed. More detailed maps are available for each Bundesland, of course they use more memory. However, since many recreational pilots mostly fly in the near to middle vicinity of their home base and since even cross-country flights usually do not zigzag through all of Germany, the memory requirements should not be an issue on today's devices.

Example: Schleswig-Holstein/Hamburg/Mecklenburg-Vorpommern uses approx. 500 MB. For many pilots north of the Elbe River, this covers everything they do during one season, and the advantage of getting more details is significant. Furthermore, sufficient memory given, there is no problem to install additional maps when needed.

I therefore suggest to make these more detailled maps installable as an option, just as you can do in OSMAND.

**Comment by kebekus** [comment]
I'm afraid that can't be done with reasonable effort. I tinkered around a bit
and found out that the technology of MapBox, which I use in the app, forces that
all installed maps have the same file level. So if we provide maps with high level of detail, then the respective country maps must also have high level of detail and become way too big.

A solution could be to generate the maps ourselves instead of getting them from openMapTiles, which would probably which would probably give us much smaller (or optionally: much more detailed) maps. However, this is a long-term project that I can't take care of as well....

@woodwind-enr  If you are interested ... we can talk on the phone and I'll tell you what I think needs to be done.
