### ISSUE TITLE
User feedback: FIS-FRQ is not being displayed in any case

### ISSUE THREAD

**Issue by woodwind-enr** [Akaflieg-Freiburg/enroute#155]
![ohneFRQ](https://user-images.githubusercontent.com/65605447/107245574-94f4a400-6a2f-11eb-9f94-0f56bd61bf9b.jpg)
![mitFRQ](https://user-images.githubusercontent.com/65605447/107245578-958d3a80-6a2f-11eb-8ec6-33ef32bc4681.jpg)

**Comment by kebekus** [comment]
Hi,

THANKS! This is a problem of the "open flightmaps" data for the region "Germany". I have already discussed this with people at OFM, but they are slow to respond. It might help if you send a polite request to Oliver Vorderegger <oliver.vorderegger@openflightmaps.org>, who is aware of the problem (and who is pretty much the only person who can fix the problem). I am closing this report because there is nothing that I can do.

Best,

Stefan.
