### ISSUE TITLE
Contrast of "Naturschutzgebiete"

### ISSUE THREAD

**Issue by spuckebaer** [Akaflieg-Freiburg/enroute#160]
I like very much the tnew contrast of the maps. Only the NSG green collour is a little bit to heavy for me and it takes my attention away from the other essential features. Would be nice to adapt

**Comment by kebekus** [comment]
I will look at this. It might take a while because some other issues have a higher priority at the moment.

**Comment by spuckebaer** [comment]
Perfect, THX

**Comment by kebekus** [comment]
Thanks again! Following your suggestion, I made the color a little more subtle for the next app version. I have to walk a fine line here because NRAs are extremely important in some countries, such as Austria, where there are many of them and violations are punished with extreme fines (~10k€).

Best

Stefan.
