### ISSUE TITLE
Thicker and more contrasty route line

### ISSUE THREAD

**Issue by Dzordzik** [Akaflieg-Freiburg/enroute#166]
Can be route line more thicker and more thicker and more contrasty? Especially on higher zoom? Each road is now contrasty than
route line which isnt ok I think. Why route line change color with map zoom? On lower zoom green is much more dark than on higher zoom. Thank you for solving this issue.

**Comment by kebekus** [comment]
Dear Dzordzik,

thank you for your comment. The route line changes its transparency with the map zoom because you do not need it as you get close to your airfield of destination. Once you reach your destination, the traffic circuit (and perhaps the entry procedures into your destination's control zone) become more important than the route. Especially when I approach larger airports with more complex traffic patterns (e.g. Berne, Switzerland) I found the route line rather annoying and I do not want to see it prominently. So, summing up: this is a feature, not a bug.

Best,

Stefan.
