### ISSUE TITLE
Connect to flight simulator X-Plane 10

### ISSUE THREAD

**Issue by propellertje** [Akaflieg-Freiburg/enroute#178]
Nice feature to connect to a flight simulator.

I did try EFN version 2.6.9 with X-Plane 10 but I am out of luck.

Alternative is the X-plane to GPS app but is not supported any more in the Google Play Store.
The latter is still working on a mediapd M5 10.8" and Honor 9, not on a Lenovo tab TB-8705F.
You also need to spoof the GPS location and must therfore bring the Android device in developper mode
![xplane10](https://user-images.githubusercontent.com/75831247/117022660-b399cc80-acf8-11eb-9070-91cdd35bbd9a.JPG)

PC (X-Plane 10) is connected on the same WIFI network as the Android device.
See picture

It's a nice to have feature and hope this feedback is helpful.

Kind regards, Bernard

**Comment by GeorgVFR** [comment]
Hi Bernard,
I just tested EFN with X-Plane 10 successfully including symbols for nearby traffic.

![enroute_X-Plane10_1](https://user-images.githubusercontent.com/64376387/117206813-972e8a80-adf3-11eb-80bd-d165e282d604.png)

Instead of enabling data output on tab "Data" please go to tab "iPhone/iPad" and enable "send AHRS data to ForeFlight, WingX Pro, or SkyDemon on ALL iPads or iPhones". Please be sure to disable output of data on tab "Data" before.

![enroute_X-Plane10_0](https://user-images.githubusercontent.com/64376387/117206592-559ddf80-adf3-11eb-8c96-24c513b25bd0.png)

A description how to connect X-Plane 10 to ForeFlight can be found here:
https://www.x-plane.com/2012/08/foreflight-charts-supported-in-x-plane-10-10-beta-9/

Regards,
Georg

**Comment by kebekus** [comment]
Thank you. I will close this issue now.

@GeorgVFR I guess you agree that I copy your text (and screenshot) to the manual?

**Comment by kebekus** [comment]
@GeorgVFR  Did I say "Thank you"? -- Thank you!

**Comment by GeorgVFR** [comment]
Thank you for this wonderful app!


> I guess you agree that I copy your text (and screenshot) to the manual?

Sure, please use everything you want.

**Comment by propellertje** [comment]
Hi Stefan and Geaorg, thank you so much! It works! on Android device. Kind regards, Bernard
![EFN_XPL10_ANDROID](https://user-images.githubusercontent.com/75831247/117859945-fa0aa080-b28f-11eb-9c24-13f865537cde.jpg)

**Comment by propellertje** [comment]
Hi Georg and Stefan, Thank you so much!!! It works!

Op do 6 mei 2021 om 23:51 schreef GeorgVFR ***@***.***>:
