### ISSUE TITLE
Adding Prohibited, Restricted and Danger areas on the map

### ISSUE THREAD

**Issue by propellertje** [Akaflieg-Freiburg/enroute#186]
Would be helpful to make the map more complete for the NL by adding the Prohibited, Restricted and Danger areas.
eAIP NL: https://www.lvnl.nl/eaip/2021-06-03-AIRAC/html/index-en-GB.html
section ENR 5 Navigation Warnings, 5.1 ---> ENR 5.1 PROHIBITED, RESTRICTED AND DANGER AREAS
Reason if an area becomes active via NOTAM notification I can plan the route accordingly taking account of the restriction.
During flight it helps me to avoid those active areas.
The graphical map can be found on the eAIP NL (Enroute Chart - ICAO) ENR 5 Navigation Warnings ---> ENR 6

**Describe alternatives you've considered**
I did consider the app https://vfrnav.com/ but EFN offer better features for my personal needs.

**Additional context**
Scrrenshot ENR 6 Enroute Chart - ICAO
![image](https://user-images.githubusercontent.com/75831247/122914755-45b66c80-d35b-11eb-937d-ffb28ff53f49.png)

Thank you for considereing this request.

Kind regards, Bernard

**Comment by kebekus** [comment]
Dear Bernard,

I am confused, because it seems to me that danger areas, restricted areas, and prohibited areas **are** shown. See the screenshots attached. Can you clarify the issue? Are there additional areas that you want to see? Do you have an example?

Best,

Stefan.

![Danger Area](https://user-images.githubusercontent.com/5110976/123038317-71cffd00-d3f0-11eb-9452-69e6eae4b781.png)
![Prohibited](https://user-images.githubusercontent.com/5110976/123038323-7399c080-d3f0-11eb-8a26-d9704bce4ab1.png)
![Restricted](https://user-images.githubusercontent.com/5110976/123038325-7399c080-d3f0-11eb-97bb-6e315b2016fd.png)

**Comment by propellertje** [comment]
Hello Stefan, Thanks for the fast response. Indeed you are right. Some areas are mentioned but not all. As an Example from my homefield EHGG due north some areas are missing. Herby enclosed one screen shot from EFR 2.8.0 and on from the orginal map NL 2021. The ENR tables mention all the areas.
![Screenshot_Area_North_EHGG](https://user-images.githubusercontent.com/75831247/123052237-e875f600-d402-11eb-94c7-1d1481fb5603.jpg)
![MAP_NL_2021_Area_North_EHGG](https://user-images.githubusercontent.com/75831247/123052277-f0359a80-d402-11eb-83d8-31f858c81cb8.jpg)

I hope this will clarify the mentioned issue.

Thank you for looking to this.

Kind regards, Bernard

**Comment by kebekus** [comment]
Am 23.06.21 um 09:12 schrieb propellertje:
>
> Hello Stefan, Thanks for the fast response. Indeed you are right. Some areas are mentioned but not all. As an Example from my homefield EHGG due north some areas are missing. Herby enclosed one screen shot from EFR 2.8.0 and on from the orginal map NL 2021. The ENR tables mention all the areas.

Dear Bernard,

I understand. This issue cannot be solved by the app, because the app simply displays air space data from the public openAIP database -- and the areas that you mention are simply not present in openAIP.

openAIP is used by many flight navigation systems. I believe that the data should absolutely be added there, and I would like to ask you to turn to the people at openAIP.net and discuss the matter with them. Peter Kemme <peter.kemme@openflightmaps.org> (in CC) knows openAIP well and has kindly volunteered to help with these issues; it would probably be a good idea to contact him first.

@Peter: Bernard pointed out that a number of (restricted|prohibited|danger) areas are missing in openAIP for the Netherlands. For examples, see the many restricted areas north of Groningen (including the EDH-R2), which are present in openFlightMaps, but not in openAIP. I attach screenshots. Would it be possible to add those? It seems that many (maybe all?) of the missing areas are "activation by NOTAM" … is there a policy at openAIP to not include those? -- Any help is greatly appreciated!

Best,

Stefan.

PS: I am closing this issue, because this cannot by solved by the app…

![Bildschirmfoto von 2021-06-24 07-12-50](https://user-images.githubusercontent.com/5110976/123206516-21be6c80-d4bc-11eb-8f05-7ecd237c6104.png)
![Bildschirmfoto von 2021-06-24 07-12-59](https://user-images.githubusercontent.com/5110976/123206524-22ef9980-d4bc-11eb-8bec-9f6dba2d286d.png)

**Comment by propellertje** [comment]
Dear Stefan, thank you very much for you're elaborate explanation and help
to resolve this issue! Kind regards, Bernard

Op do 24 jun. 2021 om 07:17 schreef Stefan Kebekus ***@***.***
