### ISSUE TITLE
Settings menu, vibration feedback

### ISSUE THREAD

**Issue by ParaJesper** [Akaflieg-Freiburg/enroute#200]
During one of the latest updates every screentap has a vibration feedback. I would like to have settings menu option to disable this.

Thnx.

**Comment by kebekus** [comment]
Dear ParaJesper,

thank you for your suggestion. Vibration feedback has always been there since the first program version, and has in my opinion proven extremely practical in real flight situations, where pilots often have only one hand, cannot listen to audio feedback, and are distracted in thousands of other ways. One of the main selling points of this app is that it is simple, and that means: as few menu options as possible. 

I summary, I prefer to keep things as they are, and hope for your understanding. The app is open-source, so please feel free to implement a menu option for yourself, if the issue is of serious importance to you.

Best,

Stefan Kebekus.
