### ISSUE TITLE
Adjustable flight path vector threshold request

### ISSUE THREAD

**Issue by bob-g4bby** [Akaflieg-Freiburg/enroute#209]
I fly a paramotor and find your app really useful. However, flying at only 17-25 mph, the flight path vector doesn't show.

Suggest the flight path vector threshold speed be user set in 'Settings'.

I really appreciate fuel prediction and taf / metar to help with planning

**Comment by kebekus** [comment]
Dear bob-g4bby,

thanks again for your suggestion. I have lowered the threshold substantially. I have decided against a new settings item because I would like to keep the app as simple as it can possibly be. The change will appear with the next program version, probably near the end of this month.

Best,

Stefan.
