### ISSUE TITLE
Add vertical speed indicator

### ISSUE THREAD

**Issue by bob-g4bby** [Akaflieg-Freiburg/enroute#210]
I've always found a vsi useful to maintain height during cruise. Is this possible to do with a little filtering to smooth out GPS jitter?

**Comment by bob-g4bby** [comment]
Closed by mistake

**Comment by kebekus** [comment]
Dear bob-g4bby,

thank you for your request. If your device reports the vertical speed, it can be seen if you open the main menu and go to "Information/Positioning". I have improved the code a bit, so that from the next program version onwards, the vertical speed will be computed and shown even if your device does not report that datum.

I understand that this is not really what you want to see; you probably want a "Primary Flight Display" on the main screen of the app. I have thought about implementing that but then decided against it: while useful only for a fraction of the audience, it makes the app heavier.

I can only ask for your understanding. I feel that the use case that you have calls for a more specialized app than I am producing.

Best,

Stefan.
