### ISSUE TITLE
Idea | Integrate as (AVITAB?-) plugin into X-Plane

### ISSUE THREAD

**Issue by anthraxn8b** [Akaflieg-Freiburg/enroute#265]
This would be a great experience - even greater in VR!
Maybe AVITAB could be used to display it...
(And YES, I know, that I can connect it (running on my Smartphone) via Network with the Sim ;-))

**Comment by kebekus** [comment]
@anthraxn8b Thank you for this idea. Much as I like the idea, I am closing this issue now because I see no chance that this feature is going to be implemented in any reasonable amount of time.

Also, it seems that the feature requires in-depth knowledge of X-Plane programming, which I do not have. I anyone from the X-Plane community is interested in implementing this feature, I will be more than glad to assist.
