### ISSUE TITLE
Idea: create circuits for airfields

### ISSUE THREAD

**Issue by TTC70** [Akaflieg-Freiburg/enroute#268]
Hey Stefan,
regarding the airfields, could it be possible to allow the user to create a traffic pattern scheme according to user inputs?
For example:
I need to arrive to "Freiburg airfield" and on Enroute i realize there is nor runaway orientation neither traffic pattern.
In the menu of "Freiburg airfield" (double tapping or keep pressed for 2 seconds) the user could choose "Add a circuit", the app asks for:
- GPS coordinates of the center of the runaway;
- runaway name (eg. 18/36);
- type of circuit (left/right);
- downwind leg's distance from the runaway.

According to these data, the app draws the traffic pattern (basically a square with smooth corners) giving to the pilot an additional indication where both runaway AND downwind leg are.

Like the user's waypoints, the new traffic pattern could be saved.

Reasons for this request.
There are several small airfields which runaways are visually barely recognizable (some airfields have even two not connected runaways). The virtual representation of the traffic pattern on the app, can represent for the pilot a huge help in order to find the related runaway and the real traffic pattern and plan the approach once the runaway is on sight.

I hope this helps.

**Comment by kebekus** [comment]
@TTC70 Thank you for your report. I have to admit that I am confused, because runway orientation and traffic pattern for Freiburg are definitively there. I attach a screenshot. Does the map look different for you? If yes, then this is a BIG bug, that must be fixed at once!

Looking forward to hearing from you,

Stefan.

![grafik](https://user-images.githubusercontent.com/5110976/206988403-ebcd59d4-12ac-46de-8a9c-54e6092a5b71.png)

**Comment by TTC70** [comment]
Stefan,
I apologize for the confusion. I wrongly used Freiburg (where the traffic
pattern exists).
If you take a look at the screenshot attached, there are two airfields,
Avio Pontinia and Pegaso Club, where there is no traffic pattern.
For Avio Pontinia there is neither runaway orientation.
My proposition was to give to the user the chance to create a traffic
pattern based on the data i wrote at the beginning, so the approach for a
specific airfield will happen with more consciousness.
Cheers


Il Lun 12 Dic 2022, 08:40 Stefan Kebekus ***@***.***> ha
scritto:

**Comment by kebekus** [comment]
@TTC70  Ok. I downgrade this to "enhancement" now. I will reply later this week.

**Comment by kebekus** [comment]
@TTC70 You address two issues here: runway orientation and traffic pattern. Both issues have solutions, but not quite the ones that you were expecting: I strongly feel that missing data should not be added in the app (on a per-user basis), but that the data should be added in the public aviation database. That way, the data needs only to be added **once**, and will then be available to **all** users of **Enroute Flight Navigation**, and all similar apps and websites. 

I (and probably much of the Italian GA community) would greatly appreciate if you would help adding the missing data. I attach explanations below. I close this issue because I believe that this is not a feature that should be added to the app.

Best wishes,

Stefan.

## Airfield data (including runway orientation)

This data comes from openAIP. Please go to [openaip.net] and open an account there: [https://www.openaip.net/new-account]. Once you have an account, you can edit airfield data and submit changes. All changes that have been approved by the openAIP maintainer will automatically appear in **Enroute Flight Navigation** within 24hrs.

## Traffic pattern

This data comes from [https://www.openflightmaps.org]. The open flightmaps work a little differently: only a few trusted project members can edit the data. Please contact Peter Kemme <peter.kemme@openflightmaps.org>, who works with open flightmaps and has kindly volunteerd to help the users of **Enroute Flight Navigation** in his spare time. Peter speaks German and English.

**Comment by TTC70** [comment]
Stefan,
Roger all.
I will try to find the time to populate airfield data.
Thanks for the suggestions.

Il Mar 13 Dic 2022, 08:24 Stefan Kebekus ***@***.***> ha
scritto:
