### ISSUE TITLE
MacOS Binary Artifacts from Github Actions?

### ISSUE THREAD

**Issue by VirusPilot** [Akaflieg-Freiburg/enroute#351]
I understand that there is no downloadable MacOS binary available but instead of building it individually I suggest that such binaries are made available as "artifacts" in the "Compile on Mac" action.

**Comment by kebekus** [comment]
@VirusPilot I do not have access to an Apple computer, I do not know how to turn the compiled binaries into a DMG, and I won't be able to do any testing. Would you happen to know how to do these things? If so, could you suggest a suitable GitHub action? I will be more than glad to follow your suggestions.

**Comment by kebekus** [comment]
@VirusPilot We are interested in offering Enroute for Apple desktop computers, but so far we lack the necessary manpower to maintain an Apple port. Would you be interested in joining the development team?

**Comment by schneisi** [comment]
I currently don't have the time resources for it, but I will take a look as soon as I have the time

**Comment by VirusPilot** [comment]
> @VirusPilot We are interested in offering Enroute for Apple desktop computers, but so far we lack the necessary manpower to maintain an Apple port. Would you be interested in joining the development team?

Well, I am not a real developer anymore so let me first try to create binaries from Github Actions. I have successfully created such binaries in my SoftRF fork so maybe I just just try here as well.

**Comment by kebekus** [comment]
@VirusPilot Thanks. Looking forward to that!

**Comment by VirusPilot** [comment]
So the first MacOS build artifacts can be downloaded in my fork but I still need to understand what is missing to build a MacOS app.

**Comment by kebekus** [comment]
@VirusPilot Does this help: https://doc.qt.io/qt-6/macos-deployment.html

**Comment by VirusPilot** [comment]
@kebekus Yes, will look into it ...

**Comment by kebekus** [comment]
@VirusPilot Enroute is a fairly complex build, so I experimented first with Enroute's smaller brother, the "Add Times" app. Could you please look at the automatically-generated "developer builds" and let me know if these work for you?

- https://github.com/Akaflieg-Freiburg/addhoursandminutes/releases/tag/developerBuilds

**Comment by VirusPilot** [comment]
Thanks for the hint, I will look into it. My daytime job is currently keeping me busy so this may take some time.

**Comment by mipastgt** [comment]
I gave the above developer build a try on my Mac and I was able to install and run the program. However, I was not able to do anything reasonable with it, but this may be due to the fact that I neither know what this program is supposed to do nor what it is supposed to look like when it works properly.

I could offer some help in testing, as I am also interested in a Mac version of the program. I could also provide some help on building a fully customized DMG installer based on a working .app file. I have automated the icon, background and DMG creation with Retina support. If you are interested, just let me know. I have attached an image of my customized DMG installer for the upcoming new release of the AIP Browser DE in order to give you an idea how it could look like.

<img width="882" alt="000_mac_AIPBrowserDE" src="https://github.com/Akaflieg-Freiburg/enroute/assets/16735714/2274a297-854e-47bf-8399-3f7ef8b759b0">

**Comment by kebekus** [comment]
@mipastgt Thanks! The app is a little calculator app. Check the [website](https://akaflieg-freiburg.github.io/addhoursandminutes/), where you can also run the app inside your browser.

Thanks also for your offer to help with DMG creation. I am working on compiling Enroute for MacOS, but since we moved to new versions of the underlying libraries, this is not straightforward and will take a few weeks. I will keep you updated via this channel.

**Comment by mipastgt** [comment]
Ok, so the functionality seems to work and looks identical to the output of the web version. But the Menu in the upper left doesn't seem to work every second time when you start the application. When it works, the corresponding texts are displayed and can be closed by pressing the OK button. But the next time you start the application it looks like this:
<img width="846" alt="Bildschirmfoto1" src="https://github.com/Akaflieg-Freiburg/enroute/assets/16735714/b59fdea3-29e2-44a4-89b5-c7fd22529b1e">
<img width="846" alt="Bildschirmfoto2" src="https://github.com/Akaflieg-Freiburg/enroute/assets/16735714/d6969b28-01f8-4e99-b355-f967d8aabb8a">
After another restart it works again and so on.

**Comment by kebekus** [comment]
@mipastgt Thanks! I will come back to you, but this will take a while…

**Comment by VirusPilot** [comment]
> @VirusPilot Enroute is a fairly complex build, so I experimented first with Enroute's smaller brother, the "Add Times" app. Could you please look at the automatically-generated "developer builds" and let me know if these work for you?
> 
> * https://github.com/Akaflieg-Freiburg/addhoursandminutes/releases/tag/developerBuilds

No, even with some modifications I can't get gh actions to produce something reasonable. Giving up for the time being ...

**Comment by kebekus** [comment]
@VirusPilot You can find an experimental binary for macOS her: https://v2202001110709105590.ultrasrv.de/nextcloud/index.php/s/sTzMTL7N9j67ose

Automatic generation via a GitHub action still doesn't work, though.

**Comment by VirusPilot** [comment]
Won't launch on my iMac 14.2.1 (23C71): "Du kannst das Programm „enroute.app“ nicht öffnen, da dieses Programm auf diesem Mac nicht unterstützt wird."

**Comment by mipastgt** [comment]
This version of the enroute.app is for ARM only. It's not universal like the previous one from Dec. 17th.

**Comment by VirusPilot** [comment]
Ah so where can I find the Intel version from Dec. 17th?

**Comment by kebekus** [comment]
I don't have that anymore. Will try to make a universal app. Give me a day or two.

**Comment by VirusPilot** [comment]
Yes, awesome!

**Comment by mipastgt** [comment]
Yes, here too.

**Comment by VirusPilot** [comment]
I even connected my Stratux and can see traffic on the map.

**Comment by kebekus** [comment]
Very well. I will work on the GitHub Actions, but currently, none of the macOS runners seem to work.

**Comment by mipastgt** [comment]
Have you checked your spending limits? https://docs.github.com/en/billing/managing-billing-for-github-actions/managing-your-spending-limit-for-github-actions

**Comment by kebekus** [comment]
Implemented. GitHub will automatically generate "Developer Builds" for a variety of platforms, including macOS. You find the binaries at https://github.com/Akaflieg-Freiburg/enroute/releases/tag/developerBuilds

**Comment by VirusPilot** [comment]
Perfect, you made my day.
