### ISSUE TITLE
Show aerobatic boxes on map

### ISSUE THREAD

**Issue by fly-shadok** [Akaflieg-Freiburg/enroute#380]
Just noticed that aerobatic flight boxes in German airspace are not shown on the map as they are on Eisenschmidt paper maps. As these are often used for aerobatics training, it would be useful to show them even though FIS is usually notified if aerobatics take place.

**Describe the solution you'd like**
Symbols on the map marking aerobatic boxes as defined in AIP VFR ENR 1-76 to 1-85. Neither altitude limits nor operating times are necessary, they should just serve as a heads-up reminder. The AIP format seems machine-readable to me, maybe something like the NOTAM system would suffice?

**Describe alternatives you've considered**
This could also be done on the openFlightMaps level, but they don't have a feature request option as far as I see.

**Additional context**
As the Eisenschmidt aerobatics symbol can't be used obviously (and shouldn't, because it's awful), I would suggest a simple "looping" symbol, something like what I cobbled together here:

![loop](https://github.com/Akaflieg-Freiburg/enroute/assets/104712533/fd12df76-a09b-487b-bf0e-4a696d3fbbd6)

Thanks for the great work anyway!

**Comment by kebekus** [comment]
@fly-shadok Thank you for the suggestion. I am supportive in principle, but I strongly feel that the data should be added to "open flightmaps" or "openAIP." 

Reason 1: Enroute currently supports 60+ countries. This is possible because we can build on the community efforts at openAIP and open flightmaps to collect the data. Adding nation-specific data sources is a significant pain and can quickly lead to more effort than our small team can handle.

Reason 2: Data added to openAIP is available worldwide and can be used in other apps, avionics devices, printed aviation maps, etc etc

@fly-shadok Please send me a private e-mail, and I can get you in touch with the relevant people at openAIP and open flightmaps. I would rather not post their e-mail addresses on this public web site.

**Comment by fly-shadok** [comment]
Hallo,

ich antworte jetzt einfach mal auf diese Mail, weil ich sonst keine Adresse finde.

Hast absolut recht, am besten wärs natürlich direkt in open flightmaps/AIP, damit auch andere darauf basierende Apps die Boxen anzeigen können.

Gruß, Gunter.

**Comment by kebekus** [comment]
@fly-shadok I am closing this issue because we agree that the data should be added to openAIP. Once the data is available there, I will be more than happy to show it in Enroute.
