### ISSUE TITLE
PJE areas remove 

### ISSUE THREAD

**Issue by 2dylan1** [Akaflieg-Freiburg/enroute#386]
Hey there, I would like it if a person had a button to switch off the PJE circles as it will declutter the map

So where you switch the altitude limits and gliding sectors off, there can be a button to witch of the PJE areas

Because of the red circles i keep thinking its part of a controlled area or danger areas or restricted areas

I will attach a screenshot 

![Screenshot_2024-03-01-12-25-28-739_de akaflieg_freiburg enroute-edit](https://github.com/Akaflieg-Freiburg/enroute/assets/119488451/978518ca-c0c0-4187-8598-e682794fc216)

**Comment by kebekus** [comment]
@2dylan1 Thanks for the report. Interestingly, this is more complicated than it looks.

Generally speaking, we are hesitant to offer options that allow to hide specific map features. Reason: the main selling point of Enroute Flight Navigation is "simplicity". We are working hard to reduce the number of options to a bare minimum, and we would rather remove a few options than adding new ones.

Unfortunately, the situation is still more difficult. If you look at the maps, you will find that PJE zones in the Netherlands are shown much more prominently than, say, in Germany. If you go to openAIP.net, you will see that PJE zones in the Netherlands are classified as "Danger Zones". In Germany, they are "Aerial Sporting Or Recreational Activity". Adding an option to switch off danger zones is of course insanely ill-advised.

I do not understand the dutch airspace, and I do not if the PJE zones are classified as "danger zones" in your AIP, or if this is something that the openAIP community has come up with. I recommend contacting the openAIP discussion board to find out and perhaps re-classify the airspaces.

I am closing the issue here because I feel that issue should not be addressed in Enroute. I know that might not be the answer that you preferred and ask for your understanding.

Please keep reporting issues that you might find!
