### ISSUE TITLE
Read GPS from network

### ISSUE THREAD

**Issue by Yameyo** [Akaflieg-Freiburg/enroute#42]
A very selfish suggestion, but if Enroute could read the GPS data broadcast by Xplane it would be the perfect companion moving map. 

Thank you for this great app.

**Comment by kebekus** [comment]
Dear Yameyo, thank you for your suggestion! Regretfully, I do not have the resources to implement the feature that you describe -- I develop the app in my spare time and concentrate on real flight rather than simulation. However, this app is open source, so everybody is welcome to join the development and extend the app in any direction. If someone else implements the feature, please let me know and I will consider including it in the main development branch.
I know that this is not the answer you wanted to hear, but I ask for your understanding that resources are limited and decisions have to be made.
Best, Stefan.
