### ISSUE TITLE
can t connect

### ISSUE THREAD

**Issue by Perry17532** [Akaflieg-Freiburg/enroute#460]
![Screenshot_20241101_104049](https://github.com/user-attachments/assets/c02921af-a378-4c89-8057-e2c00c151b90)

MSFS 2020 is running. Cessna 152 is activ at Norderney (EDWY). fs2ll is running and connectet. port 2000 is open in firewall under "incomming rules" (Eingehende Regeln.). Error like screenshot is still happening. 

Are there a solution to fix it? Maybee i am wrong. Where?

Can you help, pls.

Have a nice day.

Perry

**Desktop (please complete the following information):**
 - OS: Win 11
 - Browser firefox
 - Version 132.0 (64 bit)

**Smartphone (please complete the following information):**
 - Device: Samsung S7 FE 5G(Tablett)
 - OS: Android 14
 - Browser standard on android 14

**Comment by TTC70** [comment]
You didn't write anything about FSUIPC7.
Do you have it running?

FS2FF uses FSUIPC7 in order to send airplane position and flight data to Enroute.

**Comment by Perry17532** [comment]
don´t know. It is installed but if it is running? how to check?

**Comment by TTC70** [comment]
> don´t know. It is installed but if it is running? how to check?
> 
> can´t find in Task-Manager: nore in Processe, not in Details or Services.

It should be in the tray bar. If you don't see it then you have to launch manually. FSUIPC7 is mandatory for FS2FF to work.
Anyway if you launch it and it is already in execution, the program itself will tell you that it is already running.

**Comment by Perry17532** [comment]
i installed the newest fsuipc7 and started the sim with it. fs2ll is connected. Problem still exist.

**Comment by TTC70** [comment]
> i installed the newest fsuipc7 and started the sim with it. fs2ll is connected. Problem still exist.

What i can tell you is that the connection is pretty straightforward.
Settings to verify:
- Device IP on the wifi network - both computer and device must be in the same mask 192.168.1.xx - for instance, computer 192.168.1.10 and device 192.168.1.15.
- MSFS, FSUIPC7 and fs2ff up and running.
I have this configuration and I don't have any issue at all.
Try to configure fs2ff manually, uncheck the "auto connect" box and write the IP of the device onto fs2ff manually under the field "DEVICE IP", uncheck the "Auto-detect" box.
The only reason the device is not connected to the PC (I am NOT talking about Enroute connected with MSFS/FSUIPC7) is because they do not have the same IP configuration.

**Comment by Perry17532** [comment]
Hi there,
thanks a lot for your advice. I changed to a payware. This one works as soon as it was installed. I was too frustrated with the fs2ll. 
But anyhow. Thank you a lot.

By
Perry
