### ISSUE TITLE
Filter criteria / Display per zoom level

### ISSUE THREAD

**Issue by spuckebaer** [Akaflieg-Freiburg/enroute#73]
EDHE as the airfield with the most take-offs in Germany is filtered out in the first zoom level.
2 suggestions:
1) Please name the filter criteria in the manual to draw attention
2) Give the user the opportunity to change the settings (I suspect it is due to the grass runway)

**Comment by kebekus** [comment]
Dear Spuckebaer,

I have done some research, and it turned out that the feature is very hard to implement with the technology that we are currently using. Given the number of high-priority issues, I cannot see that this feature will be implemented in the near future, and I will therefore close this issue now.

I can only ask for your understanding and hope that you are not totally upset. We are a very small team of spare-time-programmers and need to prioritize what we are doing. If you or anyone else is interested in implementing this feature, I will be glad to help.

Best,

Stefan.
